export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_PATIENT_CATEGORIES_SUCCESS = 'FETCH_PATIENT_CATEGORIES_SUCCESS';
export const FETCH_ADD_CATEGORY_SUCCESS = 'FETCH_ADD_CATEGORY_SUCCESS';
export const FETCH_UPDATE_CATEGORY_SUCCESS = 'FETCH_UPDATE_CATEGORY_SUCCESS';
export const FETCH_DELETE_CATEGORY_SUCCESS = 'FETCH_DELETE_CATEGORY_SUCCESS';
export const FETCH_ADD_CATEGORIES_TO_FOLDER = 'FETCH_ADD_CATEGORIES_TO_FOLDER';
export const FETCH_DELETE_CATEGORY_TO_FOLDER = 'FETCH_DELETE_CATEGORY_TO_FOLDER';

