export const FETCH_PATIENTS_PENDING = 'FETCH_PATIENTS_PENDING';
export const FETCH_PATIENTS_ERROR = 'FETCH_PATIENTS_ERROR';

export const FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
export const FETCH_ADD_PATIENT_SUCCESS = 'FETCH_ADD_PATIENT_SUCCESS';
export const CHANGE_VOICE_ASSISTANT_PENDING ='CHANGE_VOICE_ASSISTANT_PENDING';
export const CHANGE_VOICE_ASSISTANT ='CHANGE_VOICE_ASSISTANT';
export const LINK_PATIENT_SUCCESS = 'LINK_PATIENT_SUCCESS';
export const UNLINK_PATIENT_SUCCESS = 'UNLINK_PATIENT_SUCCESS';