export const FETCH_PATIENTS_PENDING = 'FETCH_PATIENTS_PENDING';
export const FETCH_PATIENTS_ERROR = 'FETCH_PATIENTS_ERROR';

export const FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS';
export const FETCH_ADD_PATIENT_SUCCESS = 'FETCH_ADD_PATIENT_SUCCESS';
export const FETCH_REMOVE_PATIENT_SUCCESS = 'FETCH_DELETE_PATIENT_SUCCESS';