export const FETCH_PICTOGRAMS_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_PICTOGRAMS_ERROR = 'FETCH_PICTOGRAMS_ERROR';

export const FETCH_PICTOGRAMS_SUCCESS = 'FETCH_PICTOGRAMS_SUCCESS';
export const FETCH_ADD_PICTOGRAM_SUCCESS = 'FETCH_ADD_PICTOGRAM_SUCCESS';
export const FETCH_UPDATE_PICTOGRAM_SUCCESS = 'FETCH_UPDATE_PICTOGRAM_SUCCESS';
export const FETCH_DELETE_PICTOGRAM_SUCCESS = 'FETCH_DELETE_PICTOGRAM_SUCCESS';
export const SELECT_PICTOGRAM_TO_PHRASE = 'SELECT_PICTOGRAM_TO_PHRASE';
export const UNSELECT_PICTOGRAM_TO_PHRASE = 'UNSELECT_PICTOGRAM_TO_PHRASE';