export const FETCH_ROUTINES_PENDING = 'FETCH_ROUTINES_PENDING';
export const FETCH_ROUTINES_ERROR = 'FETCH_ROUTINES_ERROR';

export const SEND_ROUTINE = 'SEND_ROUTINE';
export const ACCEPT_ROUTINE = 'ACCEPT_ROUTINE';