export const FETCH_TUTORS_PENDING = 'FETCH_TUTORS_PENDING';
export const FETCH_TUTORS_ERROR = 'FETCH_TUTORS_ERROR';

export const TUTORS_SIGNIN_SUCCESS = 'TUTORS_SIGNIN_SUCCESS';
export const TUTORS_SIGNUP_SUCCESS = 'TUTORS_SIGNUP_SUCCESS';
export const TUTORS_LOGOUT = 'TUTORS_LOGOUT';